General Python
==============

The Python coding style information on this page has been moved to the edX Developer's Guide. The URL of the Python style guide there is http://edx.readthedocs.org/projects/edx-developer-guide/en/latest/style_guides/python_guidelines.html.